export const projectsData = [
  {
    id: 1,
    title: "Mr. Lucass",
    description: "The website of a real estate developer.",
    image: "/images/mr-lucass.webp",
    thumbnail: "/images/thumbnails/mr-lucass-thumb.webp",
    github: "https://github.com/alexvieru1/MrLucass",
    deploy: "https://mr-lucass.com",
    contributors: [],
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React", "Node.js"],
    details:
      "Mr. Lucass was my first deployed project, a bespoke presentation website crafted for a real estate developer based in Constanta, Romania. This comprehensive platform showcases Lucass's premier properties, construction stages, strategic location insights, and detailed about and contact sections. It was a significant milestone in my development journey, allowing me to blend creativity with functionality in a real-world application.",
    createdAt: "15th of January 2024",
    category: "Real Estate Development",
    status: "Completed",
  },
  {
    id: 2,
    title: "Pizza Express",
    description: "A website for a fictional pizza joint.",
    image: "/images/pizzaExpress.webp",
    thumbnail: "/images/thumbnails/pizzaExpress-thumb1.webp",
    github: "https://github.com/alexvieru1/PizzaOrderWebsite",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: ["JavaScript", "Express.js", "HTML", "CSS", "Bootstrap"],
    details:
      "Presenting our collaborative triumph: a dynamic pizza ordering website developed by our talented team. With a user-friendly interface, enticing menu options, and seamless shopping cart functionality, our platform redefines the pizza ordering experience.",
    createdAt: "19th of April 2023",
    category: "Food & Beverage",
    status: "Completed",
  },
  {
    id: 3,
    title: "Homes & Condos Rental",
    description: "A web-based rental service based on AirBnB's API.",
    image: "/images/airbNb.webp",
    thumbnail: "/images/thumbnails/homesCondos-thumb1.webp",
    github: "https://github.com/alexvieru1/HomesAndCondoRentals",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "JavaScript",
      "Express.js",
      "React",
      "MongoDB",
      "Material-UI",
      "API Integration",
    ],
    details:
      "Introducing our collaborative triumph: a cutting-edge website for home and condo rentals, leveraging Airbnb's API to offer seamless bookings, authentic reviews, and personalized user accounts.",
    createdAt: "19th of May 2023",
    category: "Real Estate & Rentals",
    status: "Completed",
  },
  {
    id: 4,
    title: "Crystal HR Advisor",
    description: "Transportation HR website.",
    image: "/images/crystalHrAdvisor.webp",
    thumbnail: "/images/thumbnails/crystalHrAdvisor-thumb1.webp",
    github: "https://github.com/suntruxi/crystal-hrAdvisor",
    deploy: "https://crystalhradvisor.com",
    contributors: ["Ruxandra Cristescu"],
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer"],
    details:
      "Crystal HR Advisor is a specialized HR consultancy firm dedicated solely to the transportation industry. With deep expertise in HR and a keen understanding of the sector's specific needs and challenges.",
    createdAt: "25th of March 2024",
    category: "HR & Consultancy",
    status: "In Progress",
  },
  {
    id: 5,
    title: "Color Up",
    description: "Nails & Lashes saloon with e-commerce of products.",
    image: "/images/colorUp.webp",
    thumbnail: "/images/thumbnails/colorUp-thumb.webp",
    github: "https://github.com/Rzvone/colorup",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: [
      "Java",
      "Spring Boot",
      "JavaScript",
      "React",
      "API Integration",
      "Material-UI",
      "MongoDB",
      "PostgreSQL",
    ],
    details:
      "A bespoke website for a nails and lashes salon, complete with user login functionality, appointment scheduling, and a seamless e-commerce platform for beauty products.",
    createdAt: "18th of August 2023",
    category: "Beauty & E-commerce",
    status: "Completed",
  },
  {
    id: 6,
    title: "Pokemon Duel",
    description: "A battle game, based on Pokemon's official API.",
    image: "/images/pokemon.webp",
    thumbnail: "/images/thumbnails/pokemonDuel-thumb.webp",
    github: "https://github.com/Rzvone/PokemonDuel",
    contributors: ["Razvan Bobonea", "Mihnea Zarafin"],
    technologies: ["JavaScript", "Express.js", "React", "API Integration"],
    details:
      "A thrilling website inspired by the Pokémon universe, where players embark on a real-world adventure to capture Pokémon through strategic duels.",
    createdAt: "4th of May 2023",
    category: "Gaming",
    status: "Prototype",
  },
];
