export const technologiesWithDetails = [
  { id: 1, name: "Next.js", designation: "Framework", image: "/images/technologies/nextjs.webp" },
  { id: 2, name: "TypeScript", designation: "Programming Language", image: "/images/technologies/typescript.webp" },
  { id: 3, name: "Java", designation: "Programming Language", image: "/images/technologies/java.webp" },
  { id: 4, name: "Spring Boot", designation: "Framework", image: "/images/technologies/spring-boot.webp" },
  { id: 5, name: "Docker", designation: "Containerization Platform", image: "/images/technologies/docker1.webp" },
  { id: 6, name: "JavaScript", designation: "Programming Language", image: "/images/technologies/javascript.png" },
  { id: 7, name: "React", designation: "Library", image: "/images/technologies/react.svg" },
  { id: 8, name: "Node.js", designation: "Runtime Environment", image: "/images/technologies/node-js.webp" },
  { id: 9, name: "Express.js", designation: "Framework", image: "/images/technologies/express-js.png" },
  { id: 10, name: "API", designation: "Interface", image: "/images/technologies/api1.webp" },
  { id: 11, name: "MongoDB", designation: "Database", image: "/images/technologies/mongo-db1.webp" },
  { id: 12, name: "PostgreSQL", designation: "Database", image: "/images/technologies/postgres.png" },
  { id: 13, name: "HTML", designation: "Markup Language", image: "/images/technologies/html2.webp" },
  { id: 14, name: "CSS", designation: "Style Sheet Language", image: "/images/technologies/css.webp" },
  { id: 15, name: "Framer", designation: "Prototyping Tool", image: "/images/technologies/framer3.png" },
  { id: 16, name: "Tailwind CSS", designation: "CSS Framework", image: "/images/technologies/tailwind-css.png" },
];
